# Generated by Django 6.0.1 on 2026-01-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (إنجليزي)')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرف')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='restaurant_categories/', verbose_name='الأيقونة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_categories/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تصنيف مطعم',
                'verbose_name_plural': 'تصنيفات المطاعم',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المطعم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('logo', models.ImageField(upload_to='restaurants/logos/', verbose_name='الشعار')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/', verbose_name='صورة الغلاف')),
                ('restaurant_type', models.CharField(choices=[('food', 'مطعم'), ('grocery', 'بقالة'), ('pharmacy', 'صيدلية'), ('sweets', 'حلويات'), ('bakery', 'مخبز'), ('coffee', 'قهوة'), ('other', 'أخرى')], default='food', max_length=20, verbose_name='نوع المتجر')),
                ('address', models.CharField(max_length=500, verbose_name='العنوان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_open', models.BooleanField(default=True, verbose_name='مفتوح')),
                ('opening_time', models.CharField(default='08:00', help_text='صيغة 24 ساعة (مثال: 08:00)', max_length=5, verbose_name='وقت الفتح')),
                ('closing_time', models.CharField(default='23:00', help_text='صيغة 24 ساعة (مثال: 23:00)', max_length=5, verbose_name='وقت الإغلاق')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('delivery_time_estimate', models.CharField(default='30-45', help_text='بالدقائق (مثال: 30-45)', max_length=50, verbose_name='وقت التوصيل المقدر')),
                ('has_discount', models.BooleanField(default=False, verbose_name='يوجد خصم')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('discount_start_time', models.CharField(blank=True, help_text='صيغة 24 ساعة', max_length=5, verbose_name='وقت بداية الخصم')),
                ('discount_end_time', models.CharField(blank=True, help_text='صيغة 24 ساعة', max_length=5, verbose_name='وقت نهاية الخصم')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='إجمالي الطلبات')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='متوسط التقييم')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='restaurants.restaurantcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مطعم',
                'verbose_name_plural': 'المطاعم',
                'ordering': ['-is_featured', '-average_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('day', models.IntegerField(choices=[(0, 'السبت'), (1, 'الأحد'), (2, 'الاثنين'), (3, 'الثلاثاء'), (4, 'الأربعاء'), (5, 'الخميس'), (6, 'الجمعة')], verbose_name='اليوم')),
                ('opening_time', models.CharField(max_length=5, verbose_name='وقت الفتح')),
                ('closing_time', models.CharField(max_length=5, verbose_name='وقت الإغلاق')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلق')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='restaurants.restaurant', verbose_name='المطعم')),
            ],
            options={
                'verbose_name': 'ساعات العمل',
                'verbose_name_plural': 'ساعات العمل',
                'ordering': ['day'],
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_active', 'is_open'], name='restaurants_is_acti_291d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['restaurant_type'], name='restaurants_restaur_876c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['category'], name='restaurants_categor_6c136e_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['average_rating'], name='restaurants_average_ec7bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['total_orders'], name='restaurants_total_o_250b15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantworkinghours',
            unique_together={('restaurant', 'day')},
        ),
    ]
