# Generated by Django 5.0.7 on 2026-01-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('food', 'مطعم')], default='food', max_length=20, verbose_name='نوع المتجر'),
        ),
    ]
