# Generated by Django 5.0.7 on 2026-01-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('food', 'مطعم'), ('grocery', 'بقالة'), ('pharmacy', 'صيدلية'), ('sweets', 'حلويات'), ('bakery', 'مخبز'), ('coffee', 'قهوة'), ('other', 'أخرى')], default='food', max_length=20, verbose_name='نوع المتجر'),
        ),
    ]
