# Generated by Django 5.0.7 on 2026-02-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_add_english_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='الشعار'),
        ),
    ]
