# Generated by Django 5.0.7 on 2026-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='app_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='النسبة المئوية التي يأخذها التطبيق كتخفيض من المطعم (مثال: 10 تعني 10%)', max_digits=5, verbose_name='نسبة تخفيض التطبيق'),
        ),
    ]
