# Generated by Django 5.0.7 on 2026-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_app_discount_percentage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurant',
            name='restaurants_categor_6c136e_idx',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurants.restaurantcategory', verbose_name='التصنيفات'),
        ),
    ]
