# Generated by Django 5.0.7 on 2026-01-13 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المحافظة')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرف')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنطقة')),
                ('slug', models.SlugField(verbose_name='المعرف')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='addresses.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'منطقة',
                'verbose_name_plural': 'المناطق',
                'ordering': ['name'],
                'unique_together': {('governorate', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: المنزل، العمل', max_length=100, verbose_name='عنوان المكان')),
                ('district', models.CharField(max_length=100, verbose_name='الحي')),
                ('street', models.CharField(max_length=200, verbose_name='الشارع')),
                ('building_number', models.CharField(blank=True, max_length=50, verbose_name='رقم البناية')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='الطابق')),
                ('apartment', models.CharField(blank=True, max_length=50, verbose_name='رقم الشقة')),
                ('landmark', models.CharField(blank=True, help_text='مثال: قرب مسجد', max_length=200, verbose_name='علامة مميزة')),
                ('additional_notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('is_current', models.BooleanField(default=False, verbose_name='العنوان الحالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='addresses.area', verbose_name='المنطقة / المدينة')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='addresses.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
                'ordering': ['-is_current', '-created_at'],
            },
        ),
    ]
