# Generated by Django 6.0.1 on 2026-01-21 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('wallet', 'محفظة')], max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('failed', 'فشل'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('currency', models.CharField(default='SYP', max_length=3, verbose_name='العملة')),
                ('transaction_id', models.CharField(blank=True, max_length=255, verbose_name='معرف المعاملة')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='استجابة البوابة')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الدفع')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الفشل')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاسترداد')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الاسترداد')),
                ('refund_reason', models.TextField(blank=True, verbose_name='سبب الاسترداد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('transaction_type', models.CharField(choices=[('payment', 'دفع'), ('refund', 'استرداد'), ('verification', 'تحقق')], default='payment', max_length=20, verbose_name='نوع المعاملة')),
                ('is_successful', models.BooleanField(default=False, verbose_name='ناجحة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('gateway', models.CharField(blank=True, max_length=50, verbose_name='البوابة')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='معرف المعاملة في البوابة')),
                ('gateway_response', models.JSONField(default=dict, verbose_name='استجابة البوابة')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='رمز الخطأ')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'معاملة دفع',
                'verbose_name_plural': 'معاملات الدفع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('transaction_type', models.CharField(choices=[('credit', 'إضافة'), ('debit', 'خصم'), ('refund', 'استرداد')], max_length=20, verbose_name='نوع المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الرصيد بعد')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order', verbose_name='الطلب')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'معاملة محفظة',
                'verbose_name_plural': 'معاملات المحفظة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'status'], name='payments_pa_method_c0b72b_idx'),
        ),
    ]
