# Generated by Django 6.0.1 on 2026-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل الأساسية')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حد التوصيل المجاني')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('driver_search_radius_km', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='نطاق البحث عن السائق (كم)')),
                ('driver_accept_timeout_seconds', models.PositiveIntegerField(default=60, verbose_name='مهلة قبول السائق (ثانية)')),
                ('recommended_weight_rating', models.DecimalField(decimal_places=2, default=0.4, max_digits=3, verbose_name='وزن التقييم في التوصيات')),
                ('recommended_weight_orders', models.DecimalField(decimal_places=2, default=0.3, max_digits=3, verbose_name='وزن الطلبات في التوصيات')),
                ('recommended_weight_recent', models.DecimalField(decimal_places=2, default=0.3, max_digits=3, verbose_name='وزن الطلبات الأخيرة في التوصيات')),
                ('recent_orders_days', models.PositiveIntegerField(default=30, verbose_name='عدد أيام الطلبات الأخيرة')),
                ('app_version', models.CharField(default='1.0.0', max_length=20, verbose_name='إصدار التطبيق')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='رسالة الصيانة')),
            ],
            options={
                'verbose_name': 'إعدادات التطبيق',
                'verbose_name_plural': 'إعدادات التطبيق',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='العنوان الفرعي')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='الصورة')),
                ('banner_type', models.CharField(choices=[('ramadan', 'رمضان'), ('eid', 'عيد'), ('promotion', 'عرض'), ('seasonal', 'موسمي'), ('general', 'عام')], default='general', max_length=20, verbose_name='نوع البانر')),
                ('link', models.CharField(blank=True, help_text='رابط داخلي أو خارجي', max_length=500, verbose_name='الرابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'بانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
