# Generated by Django 5.0.7 on 2026-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_english_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='free_distance_km',
            field=models.DecimalField(decimal_places=2, default=3, help_text='المسافة المشمولة برسوم التوصيل الأساسية', max_digits=5, verbose_name='المسافة الأساسية (كم)'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='max_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 يعني بدون حد أقصى', max_digits=10, verbose_name='الحد الأقصى لرسوم التوصيل'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='per_km_fee',
            field=models.DecimalField(decimal_places=2, default=3000, help_text='رسوم كل كيلومتر إضافي بعد المسافة الأساسية (ل.س)', max_digits=10, verbose_name='رسوم الكيلومتر الإضافي'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=12000, help_text='رسوم التوصيل للمسافة الأساسية (ل.س)', max_digits=10, verbose_name='رسوم التوصيل الأساسية'),
        ),
    ]
