# Generated by Django 5.0.7 on 2026-02-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appconfiguration_free_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='max_delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=15, help_text='أقصى مسافة بين المستخدم والمطعم لعرضه في التطبيق', max_digits=5, verbose_name='أقصى نطاق توصيل (كم)'),
        ),
    ]
