# Generated by Django 5.2.5 on 2026-03-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appconfiguration_max_delivery_radius_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='preparation_lead_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='دقائق التحضير'),
        ),
    ]
