# Generated by Django 5.2.5 on 2026-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appconfiguration_preparation_lead_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='min_online_drivers',
            field=models.PositiveIntegerField(default=0, help_text='0 يعني بدون حد أدنى. إذا حاول سائق الخروج وعدد المتصلين سينقص عن هذا الحد، سيُمنع', verbose_name='الحد الأدنى للسائقين المتصلين'),
        ),
    ]
