# Generated by Django 6.0.1 on 2026-01-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الكوبون')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='للخصم بالنسبة المئوية', max_digits=10, null=True, verbose_name='الحد الأقصى للخصم')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ النهاية')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='حد الاستخدام الكلي')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=1, verbose_name='حد الاستخدام لكل مستخدم')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستخدام')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للطلب')),
                ('first_order_only', models.BooleanField(default=False, verbose_name='للطلب الأول فقط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('restaurant', models.ForeignKey(blank=True, help_text='اتركه فارغاً لتطبيقه على جميع المطاعم', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='restaurants.restaurant', verbose_name='المطعم')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الخصم')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon', verbose_name='الكوبون')),
            ],
            options={
                'verbose_name': 'استخدام كوبون',
                'verbose_name_plural': 'استخدامات الكوبونات',
                'ordering': ['-created_at'],
            },
        ),
    ]
