# Generated by Django 5.0.7 on 2026-01-13 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='الاسم الأخير')),
                ('governorate', models.CharField(choices=[('damascus', 'دمشق'), ('rif_dimashq', 'ريف دمشق'), ('aleppo', 'حلب'), ('homs', 'حمص'), ('hama', 'حماة'), ('latakia', 'اللاذقية'), ('tartous', 'طرطوس'), ('idlib', 'إدلب'), ('deir_ez_zor', 'دير الزور'), ('raqqa', 'الرقة'), ('hasakah', 'الحسكة'), ('daraa', 'درعا'), ('suwayda', 'السويداء'), ('quneitra', 'القنيطرة')], max_length=20, verbose_name='المحافظة')),
                ('role', models.CharField(choices=[('user', 'مستخدم'), ('admin', 'مدير'), ('driver', 'سائق')], default='user', max_length=10, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الانضمام')),
                ('is_online', models.BooleanField(default=False, verbose_name='متصل')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='الرمز')),
                ('otp_type', models.CharField(choices=[('signup', 'تسجيل حساب'), ('forgot_password', 'نسيت كلمة المرور')], max_length=20, verbose_name='نوع الرمز')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز التحقق',
                'verbose_name_plural': 'رموز التحقق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('total_online_seconds', models.PositiveIntegerField(default=0, verbose_name='Total Online Seconds')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='Total Sessions')),
                ('first_online', models.DateTimeField(blank=True, null=True, verbose_name='First Online')),
                ('last_offline', models.DateTimeField(blank=True, null=True, verbose_name='Last Offline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Driver Daily Stats',
                'verbose_name_plural': 'Driver Daily Stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['driver', 'date'], name='accounts_dr_driver__2b85cd_idx')],
                'unique_together': {('driver', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Start Time')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Session')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Session',
                'verbose_name_plural': 'Driver Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['driver', 'date'], name='accounts_dr_driver__d302b3_idx'), models.Index(fields=['driver', 'is_active'], name='accounts_dr_driver__ed8934_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, verbose_name='Status')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL, verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Driver Work Log',
                'verbose_name_plural': 'Driver Work Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', 'timestamp'], name='accounts_dr_driver__79f3e6_idx'), models.Index(fields=['driver', 'status', 'timestamp'], name='accounts_dr_driver__db1b3e_idx')],
            },
        ),
    ]
