# Generated by Django 5.0.7 on 2026-01-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='governorate',
            field=models.CharField(blank=True, choices=[('damascus', 'دمشق'), ('rif_dimashq', 'ريف دمشق'), ('aleppo', 'حلب'), ('homs', 'حمص'), ('hama', 'حماة'), ('latakia', 'اللاذقية'), ('tartous', 'طرطوس'), ('idlib', 'إدلب'), ('deir_ez_zor', 'دير الزور'), ('raqqa', 'الرقة'), ('hasakah', 'الحسكة'), ('daraa', 'درعا'), ('suwayda', 'السويداء'), ('quneitra', 'القنيطرة')], max_length=20, null=True, verbose_name='المحافظة'),
        ),
    ]
