# Generated by Django 5.0.7 on 2026-01-24 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_governorate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverdailystats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='driverdailystats',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverworklog',
            name='driver',
        ),
        migrations.AlterModelOptions(
            name='driversession',
            options={'ordering': ['-started_at'], 'verbose_name': 'جلسة عمل', 'verbose_name_plural': 'جلسات العمل'},
        ),
        migrations.RemoveField(
            model_name='driversession',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='driversession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='driversession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='المدة (ثواني)'),
        ),
        migrations.AddField(
            model_name='driversession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='date',
            field=models.DateField(db_index=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='السائق'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='جلسة نشطة'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='started_at',
            field=models.DateTimeField(verbose_name='وقت البداية'),
        ),
        migrations.AddIndex(
            model_name='driversession',
            index=models.Index(fields=['date', 'driver'], name='accounts_dr_date_f874f9_idx'),
        ),
        migrations.DeleteModel(
            name='DriverDailyStats',
        ),
        migrations.DeleteModel(
            name='DriverWorkLog',
        ),
    ]
