# Generated by Django 5.0.7 on 2026-01-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_driverdailystats_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driversession',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='driversession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت البداية'),
        ),
    ]
