# Generated by Django 5.0.7 on 2026-02-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_driversession_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='رقم البطل')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البطل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='heroes/', verbose_name='صورة البطل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'بطل',
                'verbose_name_plural': 'الأبطال',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='hero',
            field=models.ForeignKey(blank=True, help_text='البطل الذي اختاره السائق', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='accounts.hero', verbose_name='البطل'),
        ),
    ]
