# Generated by Django 5.2.5 on 2026-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hero_user_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم البطل (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2, verbose_name='اللغة المفضلة'),
        ),
    ]
