# Generated by Django 5.2.5 on 2026-03-02 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hero_name_en_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='التاريخ')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='المدة (ثواني)')),
                ('is_active', models.BooleanField(default=True, verbose_name='جلسة نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('admin_user', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'جلسة عمل مشرف',
                'verbose_name_plural': 'جلسات عمل المشرفين',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['admin_user', 'date'], name='accounts_ad_admin_u_875739_idx'), models.Index(fields=['admin_user', 'is_active'], name='accounts_ad_admin_u_1757db_idx'), models.Index(fields=['date', 'admin_user'], name='accounts_ad_date_ecba17_idx')],
            },
        ),
    ]
