# Generated by Django 5.2.5 on 2026-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_adminsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driversession',
            options={'ordering': ['-started_at'], 'verbose_name': 'جلسة عمل', 'verbose_name_plural': 'جلسات عمل السائقين'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
