# Generated by Django 5.0.7 on 2026-02-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'تقييم السائق', 'verbose_name_plural': 'تقييمات السائقين'},
        ),
    ]
