JAZZMIN_SETTINGS = {
    "site_title": "Super Driver Admin",
    "site_header": "Super Driver",
    "site_brand": "Super Driver",
    "welcome_sign": "اهلا و سهلا بكم في لوحة تحكم Super Driver",
    "copyright": "Super Driver © 2026",
    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "img/favicon.ico",
    "search_model": ["accounts.User", "orders.Order", "restaurants.Restaurant"],
    "topmenu_links": [
        {"model": "accounts.User"},
        {"model": "orders.Order"},
        {"model": "restaurants.Restaurant"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "orders",
        "restaurants",
        "menu",
        "coupons",
        "reviews",
        "notifications",
        "addresses",
        "accounts",
        "core",
    ],
    "hide_apps": [
        "cart",
        "payments",
        "auth",
        "token_blacklist",
    ],
    "hide_models": [
        "accounts.OTP",
        "cart.CartItem",
        "cart.CartItemAddon",
        "menu.ProductVariation",
        "menu.ProductAddon",
    ],
    "icons": {
        "auth": "fas fa-shield-alt",
        "accounts": "fas fa-users",
        "accounts.User": "fas fa-user",
        "accounts.OTP": "fas fa-key",
        "addresses": "fas fa-map-marked-alt",
        "addresses.Address": "fas fa-map-marker-alt",
        "addresses.Governorate": "fas fa-globe",
        "addresses.Area": "fas fa-map",
        "core": "fas fa-cogs",
        "core.Banner": "fas fa-images",
        "core.AppConfiguration": "fas fa-sliders-h",
        "restaurants": "fas fa-utensils",
        "restaurants.Restaurant": "fas fa-store",
        "restaurants.RestaurantCategory": "fas fa-tags",
        "menu": "fas fa-book-open",
        "menu.MenuCategory": "fas fa-list",
        "menu.Product": "fas fa-hamburger",
        "coupons": "fas fa-ticket-alt",
        "coupons.Coupon": "fas fa-percentage",
        "cart": "fas fa-shopping-cart",
        "cart.Cart": "fas fa-shopping-basket",
        "orders": "fas fa-receipt",
        "orders.Order": "fas fa-clipboard-list",
        "payments": "fas fa-credit-card",
        "payments.Payment": "fas fa-money-bill-wave",
        "payments.Wallet": "fas fa-wallet",
        "reviews": "fas fa-star",
        "reviews.RestaurantReview": "fas fa-comment",
        "reviews.DriverReview": "fas fa-car",
        "notifications": "fas fa-bell",
        "notifications.Notification": "fas fa-envelope",
        "notifications.BroadcastNotification": "fas fa-bullhorn",
    },
    "custom_links": {
        "restaurants": [
            {
                "name": "استيراد / تصدير المنتجات",
                "url": "import_products",  # ← اسم الـ url name
                "icon": "fas fa-file-excel",
                "permissions": ["restaurants.view_restaurant"],
            }
        ],
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "accounts.User": "vertical_tabs",
        "orders.Order": "vertical_tabs",
        "restaurants.Restaurant": "vertical_tabs",
    },
    "language_chooser": False,
    "custom_css": "css/admin-custom.css",
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "navbar_fixed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "layout_boxed": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": False,
}
