from datetime import timedelta

from config.env import env


ACCESS_TOKEN_LIFETIME_DAYS = env.int("JWT_ACCESS_TOKEN_LIFETIME_DAYS", default=365)
REFRESH_TOKEN_LIFETIME_DAYS = env.int("JWT_REFRESH_TOKEN_LIFETIME_DAYS", default=30)
ROTATE_REFRESH_TOKENS = env.bool("JWT_ROTATE_REFRESH_TOKENS", default=True)
BLACKLIST_AFTER_ROTATION = env.bool("JWT_BLACKLIST_AFTER_ROTATION", default=True)
UPDATE_LAST_LOGIN = env.bool("JWT_UPDATE_LAST_LOGIN", default=True)
ALGORITHM = env("JWT_ALGORITHM", default="HS256")


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=ACCESS_TOKEN_LIFETIME_DAYS),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=REFRESH_TOKEN_LIFETIME_DAYS),
    "ROTATE_REFRESH_TOKENS": ROTATE_REFRESH_TOKENS,
    "BLACKLIST_AFTER_ROTATION": BLACKLIST_AFTER_ROTATION,
    "UPDATE_LAST_LOGIN": UPDATE_LAST_LOGIN,
    "ALGORITHM": ALGORITHM,
    "AUTH_HEADER_TYPES": (env("JWT_AUTH_HEADER_TYPE", default="Bearer"),),
    "AUTH_HEADER_NAME": env("JWT_AUTH_HEADER_NAME", default="HTTP_AUTHORIZATION"),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}
