# Generated by Django 6.0.1 on 2026-01-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('coupons', '0001_initial'),
        ('menu', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='coupons.coupon', verbose_name='الكوبون'),
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='restaurants.restaurant', verbose_name='المطعم'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='السلة'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='menu.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='menu.productvariation', verbose_name='التنويع'),
        ),
        migrations.AddField(
            model_name='cartitemaddon',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_addons', to='menu.productaddon', verbose_name='الإضافة'),
        ),
        migrations.AddField(
            model_name='cartitemaddon',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_addons', to='cart.cartitem', verbose_name='عنصر السلة'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='cartitemaddon',
            unique_together={('cart_item', 'addon')},
        ),
    ]
