# Generated by Django 5.0.7 on 2026-01-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تنتهي في'),
        ),
    ]
