# Generated by Django 5.2.5 on 2026-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_add_english_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت'), ('free_delivery', 'توصيل مجاني')], default='percentage', max_length=20, verbose_name='نوع الخصم'),
        ),
    ]
