# Generated by Django 6.0.1 on 2026-01-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_remove_address_district_alter_address_street'),
        ('coupons', '0001_initial'),
        ('menu', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('accepted', 'تم القبول'), ('preparing', 'جاري التحضير'), ('ready', 'جاهز'), ('picked', 'تم الاستلام'), ('on_the_way', 'في الطريق'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('wallet', 'محفظة')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('failed', 'فشل'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع الفرعي')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('restaurant_snapshot', models.JSONField(default=dict, verbose_name='بيانات المطعم')),
                ('address_snapshot', models.JSONField(default=dict, verbose_name='بيانات العنوان')),
                ('items_snapshot', models.JSONField(default=list, verbose_name='بيانات المنتجات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('special_instructions', models.TextField(blank=True, verbose_name='تعليمات خاصة')),
                ('placed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الطلب')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القبول')),
                ('preparing_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء التحضير')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الجهوزية')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستلام')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التوصيل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاكتمال')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإلغاء')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='سبب الإلغاء')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت التوصيل المتوقع')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='ملغي بواسطة')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon', verbose_name='الكوبون')),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='addresses.address', verbose_name='عنوان التوصيل')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to=settings.AUTH_USER_MODEL, verbose_name='السائق')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.restaurant', verbose_name='المطعم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('action', models.CharField(choices=[('pending', 'بانتظار الرد'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'منتهي')], default='pending', max_length=20, verbose_name='الإجراء')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المسافة (كم)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الرد')),
                ('expires_at', models.DateTimeField(verbose_name='وقت الانتهاء')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to=settings.AUTH_USER_MODEL, verbose_name='السائق')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'طلب سائق',
                'verbose_name_plural': 'طلبات السائقين',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('special_instructions', models.TextField(blank=True, verbose_name='تعليمات خاصة')),
                ('product_snapshot', models.JSONField(default=dict, verbose_name='بيانات المنتج')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.product', verbose_name='المنتج')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.productvariation', verbose_name='التنويع')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلب',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('addon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_addons', to='menu.productaddon', verbose_name='الإضافة')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_addons', to='orders.orderitem', verbose_name='عنصر الطلب')),
            ],
            options={
                'verbose_name': 'إضافة عنصر طلب',
                'verbose_name_plural': 'إضافات عناصر الطلب',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('from_status', models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('accepted', 'تم القبول'), ('preparing', 'جاري التحضير'), ('ready', 'جاهز'), ('picked', 'تم الاستلام'), ('on_the_way', 'في الطريق'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], max_length=20, verbose_name='من الحالة')),
                ('to_status', models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('accepted', 'تم القبول'), ('preparing', 'جاري التحضير'), ('ready', 'جاهز'), ('picked', 'تم الاستلام'), ('on_the_way', 'في الطريق'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], max_length=20, verbose_name='إلى الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'سجل حالة الطلب',
                'verbose_name_plural': 'سجل حالات الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status'], name='orders_orde_restaur_17016b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['driver', 'status'], name='orders_orde_driver__83706f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverorderrequest',
            unique_together={('order', 'driver')},
        ),
    ]
