# Generated by Django 5.0.7 on 2026-01-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='preparing_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ready_at',
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم التواصل'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='طلب مجدول'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery_time',
            field=models.DateTimeField(blank=True, help_text='اتركه فارغاً للتوصيل الفوري', null=True, verbose_name='وقت التوصيل المطلوب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('accepted', 'تم القبول'), ('picked', 'تم الاستلام'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('accepted', 'تم القبول'), ('picked', 'تم الاستلام'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], max_length=20, verbose_name='من الحالة'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('accepted', 'تم القبول'), ('picked', 'تم الاستلام'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], max_length=20, verbose_name='إلى الحالة'),
        ),
    ]
