# Generated by Django 5.0.7 on 2026-01-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_preparing_at_remove_order_ready_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='order',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء التحضير'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التوصيل المطلوب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('preparing', 'جاري التحضير'), ('picked', 'تم الاستلام'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('preparing', 'جاري التحضير'), ('picked', 'تم الاستلام'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], max_length=20, verbose_name='من الحالة'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('preparing', 'جاري التحضير'), ('picked', 'تم الاستلام'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], max_length=20, verbose_name='إلى الحالة'),
        ),
    ]
