# Generated by Django 5.0.7 on 2026-02-01 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_accepted_at_remove_order_completed_at_and_more'),
        ('restaurants', '0005_alter_restaurant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOrder',
            fields=[
            ],
            options={
                'verbose_name': 'طلب يدوي',
                'verbose_name_plural': 'الطلبات اليدوية',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الطلب'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='طلب يدوي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.restaurant', verbose_name='المطعم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المجموع الفرعي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
