# Generated by Django 5.0.7 on 2026-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_manualorder_order_description_order_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_text',
            field=models.TextField(blank=True, verbose_name='عنوان التوصيل (نص)'),
        ),
    ]
