# Generated by Django 5.0.7 on 2026-02-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_add_english_fields'),
        ('orders', '0005_order_delivery_address_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='addresses.address', verbose_name='عنوان التوصيل'),
        ),
    ]
