# Generated by Django 5.0.7 on 2026-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='app_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة تخفيض التطبيق'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='المبلغ الذي سيتم دفعه للمطعم بعد خصم نسبة التطبيق', max_digits=10, verbose_name='المبلغ المستحق للمطعم'),
        ),
    ]
