# Generated by Django 5.0.7 on 2026-02-12 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_app_discount_percentage_order_restaurant_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverorderrequest',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='الأدمن الذي أنشأ الطلب اليدوي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_name_manual',
            field=models.CharField(blank=True, help_text='للطلبات اليدوية التي لا ترتبط بمطعم مسجل', max_length=200, verbose_name='اسم المطعم (يدوي)'),
        ),
    ]
