# Generated by Django 5.0.7 on 2026-02-17 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_driverorderrequest_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات السائق')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_reports', to=settings.AUTH_USER_MODEL, verbose_name='السائق')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_report', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'تقرير التسليم',
                'verbose_name_plural': 'تقارير التسليم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('image', models.ImageField(upload_to='delivery_reports/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.orderdeliveryreport', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'صورة تقرير',
                'verbose_name_plural': 'صور التقارير',
            },
        ),
    ]
