# Generated by Django 5.2.5 on 2026-02-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderdeliveryreport_orderdeliveryreportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تحديد السعر النهائي'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_price_pending',
            field=models.BooleanField(default=False, help_text='الدرايفر سيدخل السعر عند الاستلام من المحل', verbose_name='السعر غير محدد'),
        ),
    ]
