# Generated by Django 5.2.5 on 2026-03-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_order_final_price_set_at_order_is_price_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="chat_order_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="معرف الطلب من محادثة الشات في التطبيق",
                max_length=100,
                verbose_name="معرف طلب الشات",
            ),
        ),
    ]
