# Generated by Django 5.2.5 on 2026-03-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_chat_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التأكيد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('confirmed', 'تمت الموافقة'), ('preparing', 'جاري التحضير'), ('picked', 'تم الاستلام'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('confirmed', 'تمت الموافقة'), ('preparing', 'جاري التحضير'), ('picked', 'تم الاستلام'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], max_length=20, verbose_name='من الحالة'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('placed', 'تم الطلب'), ('confirmed', 'تمت الموافقة'), ('preparing', 'جاري التحضير'), ('picked', 'تم الاستلام'), ('delivered', 'تم التوصيل'), ('cancelled', 'ملغي')], max_length=20, verbose_name='إلى الحالة'),
        ),
    ]
