# Generated by Django 6.0.1 on 2026-01-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('users', 'Customers Only'), ('drivers', 'Drivers Only'), ('governorate', 'Specific Governorate')], default='all', max_length=50)),
                ('target_governorate', models.CharField(blank=True, help_text="Required if target_audience is 'governorate'", max_length=100, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('open_app', 'Open App'), ('open_restaurant', 'Open Restaurant'), ('open_category', 'Open Category'), ('open_url', 'Open URL')], max_length=50, null=True)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Schedule for future delivery', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('successful_sends', models.PositiveIntegerField(default=0)),
                ('failed_sends', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('order_updates', models.BooleanField(default=True, help_text='Order status updates')),
                ('promotional', models.BooleanField(default=True, help_text='Promotional offers and discounts')),
                ('new_restaurants', models.BooleanField(default=True, help_text='New restaurants in area')),
                ('review_reminders', models.BooleanField(default=True, help_text='Reminder to review orders')),
                ('driver_updates', models.BooleanField(default=True, help_text='Driver-specific notifications (for drivers)')),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification preferences',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('notification_type', models.CharField(choices=[('order_placed', 'order_placed'), ('order_accepted', 'order_accepted'), ('order_preparing', 'order_preparing'), ('order_ready', 'order_ready'), ('order_picked', 'order_picked'), ('order_on_the_way', 'order_on_the_way'), ('order_delivered', 'order_delivered'), ('order_cancelled', 'order_cancelled'), ('driver_assigned', 'driver_assigned'), ('driver_arrived', 'driver_arrived'), ('new_order_for_driver', 'new_order_for_driver'), ('promotion', 'promotion'), ('general', 'general')], default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Type of referenced object (order, restaurant, etc.)', max_length=50, null=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of referenced object', null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
    ]
