# Generated by Django 5.0.7 on 2026-01-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'order_placed'), ('order_accepted', 'order_accepted'), ('order_picked', 'order_picked'), ('order_delivered', 'order_delivered'), ('order_completed', 'order_completed'), ('order_cancelled', 'order_cancelled'), ('driver_assigned', 'driver_assigned'), ('new_order_for_driver', 'new_order_for_driver'), ('promotion', 'promotion'), ('general', 'general')], default='general', max_length=50),
        ),
    ]
