# Generated by Django 5.0.7 on 2026-02-16 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار جماعي', 'verbose_name_plural': 'الإشعارات الجماعية'},
        ),
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'ordering': ['-last_used_at'], 'verbose_name': 'توكن جهاز', 'verbose_name_plural': 'توكنات الأجهزة'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name': 'تفضيل إشعارات', 'verbose_name_plural': 'تفضيلات الإشعارات'},
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='action_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الإجراء'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='action_type',
            field=models.CharField(blank=True, choices=[('open_app', 'فتح التطبيق'), ('open_restaurant', 'فتح مطعم'), ('open_category', 'فتح تصنيف'), ('open_url', 'فتح رابط')], max_length=50, null=True, verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='body',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='المحتوى (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='failed_sends',
            field=models.PositiveIntegerField(default=0, verbose_name='إرسال فاشل'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='تم الإرسال'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='جدولة للإرسال لاحقاً', null=True, verbose_name='موعد الإرسال المجدول'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='successful_sends',
            field=models.PositiveIntegerField(default=0, verbose_name='إرسال ناجح'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='target_audience',
            field=models.CharField(choices=[('all', 'الكل'), ('users', 'الزبائن فقط'), ('drivers', 'السائقين فقط'), ('governorate', 'محافظة محددة')], default='all', max_length=50, verbose_name='الجمهور المستهدف'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='target_governorate',
            field=models.CharField(blank=True, help_text="مطلوب إذا كان الجمهور 'محافظة محددة'", max_length=100, null=True, verbose_name='المحافظة المستهدفة'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='broadcastnotification',
            name='total_recipients',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي المستلمين'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الجهاز'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_type',
            field=models.CharField(choices=[('android', 'أندرويد'), ('ios', 'iOS'), ('web', 'ويب')], max_length=20, verbose_name='نوع الجهاز'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر استخدام'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='التوكن'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='المحتوى (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'order_placed'), ('order_preparing', 'order_preparing'), ('order_picked', 'order_picked'), ('order_delivered', 'order_delivered'), ('order_cancelled', 'order_cancelled'), ('driver_assigned', 'driver_assigned'), ('new_order_for_driver', 'new_order_for_driver'), ('promotion', 'promotion'), ('general', 'general')], default='general', max_length=50, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False, verbose_name='تم الإرسال'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, help_text='معرّف العنصر المرتبط', null=True, verbose_name='معرّف المرجع'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reference_type',
            field=models.CharField(blank=True, help_text='نوع العنصر المرتبط (طلب، مطعم، إلخ)', max_length=50, null=True, verbose_name='نوع المرجع'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='driver_updates',
            field=models.BooleanField(default=True, verbose_name='تحديثات السائق'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل البريد'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='new_restaurants',
            field=models.BooleanField(default=True, verbose_name='مطاعم جديدة'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='order_updates',
            field=models.BooleanField(default=True, verbose_name='تحديثات الطلبات'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='promotional',
            field=models.BooleanField(default=True, verbose_name='العروض الترويجية'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل الإشعارات'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل ساعات الهدوء'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='نهاية ساعات الهدوء'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='بداية ساعات الهدوء'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='review_reminders',
            field=models.BooleanField(default=True, verbose_name='تذكير بالتقييم'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل الرسائل'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
