# Generated by Django 5.2.5 on 2026-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_broadcastnotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='language',
            field=models.CharField(default='ar', help_text='لغة الإشعارات (ar/en)', max_length=5, verbose_name='لغة الجهاز'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_placed', 'order_placed'), ('order_preparing', 'order_preparing'), ('order_picked', 'order_picked'), ('order_delivered', 'order_delivered'), ('order_cancelled', 'order_cancelled'), ('driver_assigned', 'driver_assigned'), ('new_order_for_driver', 'new_order_for_driver'), ('new_order_for_admin', 'new_order_for_admin'), ('promotion', 'promotion'), ('general', 'general')], default='general', max_length=50, verbose_name='نوع الإشعار'),
        ),
    ]
